name: Close Issue

on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch: # Allow for running this manually.

jobs:
  issue-to-be-closed:
    runs-on: ubuntu-latest
    steps:
      - name: close-issues
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issues'
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'to be closed'
          inactive-day: 7