name: sync to docs-h5

on:
  push:
    branches:
      - v4 # default branch
    paths:
      - '.github/workflows/**'
      - 'src/**'

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        run: corepack enable

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Copy
        run: pnpm copy:h5

      - name: Sync
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: new-site # action 应该部署到的分支 。
          folder: site_docs #操作应该部署的文件夹 。
          clean: false
          repository-name: jdf2e/nutui-docs
          token: ${{ secrets.GIT_ACTION }}
          target-folder: src/docs_vue
